// <auto-generated />
namespace FantasyForge_N01543896.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedUsermediaitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedUsermediaitem));
        
        string IMigrationMetadata.Id
        {
            get { return "202406220146195_updatedUsermediaitem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
